### ISSUE TITLE
Text Content for Interface

### ISSUE THREAD

**Issue by ruchikavn** [ruchikavn/indianrailwaymap#12]
@geohacker 

**Service Types**  <-- Heading

- Rajdhani
- Duronto
- Shatabdi + Janshatabdi
- Garib Rath
- Sampark Kranti
- Mail, Express & Superfast
- Passenger

**Comment by planemad** [comment]
Reference: https://en.wikipedia.org/wiki/Indian_Railways#Types_of_passenger_services

**Comment by geohacker** [comment]
👍

**Comment by ruchikavn** [comment]
Brief description of each service @geohacker 

**Rajdhani Express**
High speed priority trains that connect major cities to the capital

**Duronto Express**
High speed non-stop trains connecting major cities

**Shatabdi + Janshatabdi**
High speed day trains connecting metros to other cities

**Garib Rath**
High speed air-conditioned trains at subsidized rates

**Passenger**
Low-cost slow trains that halt at most or every station along the way

**Mail/Express**
High speed trains with few halts along the way

**Comment by ruchikavn** [comment]
Map title and description @geohacker 

**Visualising the Indian Railways**
Explore the map to learn how the Indian railway network is structured. Brightness of line indicates train speeds while points on the map represent terminal as well as halt stations.
